# Generated by Django 3.1.7 on 2021-03-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210318_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postuser',
            options={'ordering': ['-date_post'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
