# Generated by Django 3.1.7 on 2021-06-02 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210321_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='dislike_post',
        ),
        migrations.AddField(
            model_name='postuser',
            name='dislike_post',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='like_post',
        ),
        migrations.AddField(
            model_name='postuser',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
