# Generated by Django 3.1.7 on 2021-03-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriends',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userfriends',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userfriends',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='UserFriends',
        ),
    ]
