# Generated by Django 3.1.7 on 2021-03-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_relationship_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('deleted', 'deleted'), ('blocked', 'blocked')], max_length=8),
        ),
    ]
