# Generated by Django 3.1.7 on 2021-04-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20210331_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('deleted', 'deleted'), ('blocked', 'blocked'), ('unblocked', 'unblocked')], max_length=9),
        ),
    ]
