# Generated by Django 3.1.7 on 2021-03-07 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_user_code', models.CharField(blank=True, max_length=15, unique=True)),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('intro', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('sn_github', models.CharField(blank=True, max_length=100, null=True)),
                ('sn_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('sn_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
